#apiVersion: v1
#kind: Pod
#metadata:
#  name: nginx
#  labels:
#    app.kubernetes.io/name: proxy
#spec:
#  containers:
#    - name: nginx
#      image: web
#      ports:
#        - containerPort: 80
#          name: http-web-svc

apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  selector:
    app.kubernetes.io/name: hello-world-pod
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 80
      targetPort: http-web-svc