apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-pod
  labels:
    app: hello-world-pod
spec:
  replicas: 1
  selector:
    matchLabels:
     app: hello-world-pod
  template:
    metadata:
      name: hello-world-pod
      labels:
        app: hello-world-pod
    spec:
      containers:
        - name: hello-world-pod
          image: ghebarion/muie-psd
          imagePullPolicy: Always
          ports:
            - containerPort: 8081